### ISSUE TITLE
Используйте Environment.NewLine

### ISSUE THREAD

**Issue by lAnubisl** [sokolw/C_sharp_learning#1]
В разных платформах перенос строк осуществляется разными символами.
вместо конкретного символа используйте Environment.NewLine

https://github.com/sokolw/C_sharp_learning/blob/d48ecdced9b748c36b44e57d3fe8400ea6ea2711/homework/week7/Game.cs#L84

**Comment by sokolw** [comment]
Поместил эту сроку в отдельный класс ConsoleWords и добавил NewLine. Думаю туда забросить весь текст который выводится в коснсоль.
